import type { Task } from '../types'

// 데모 모드(아직 Supabase 미설정)에서 화면을 미리 보기 위한 샘플 데이터.
// 실제 운영에서는 Supabase 의 tasks 테이블이 이 역할을 대신한다.
export const SAMPLE_TASKS: Task[] = [
  // ── 프로젝트: 6월 신제품 런칭 ──
  {
    id: 'demo-1',
    project: '6월 신제품 런칭',
    team: '영업-마케팅(온라인)',
    title: '런칭 캠페인 기획',
    status: 'in_progress',
    progress: 60,
    start_date: '2026-06-01',
    due_date: '2026-06-20',
    slides_url: 'https://docs.google.com/presentation/d/EXAMPLE1',
    owner: '조윤성',
    notes: '핵심 메시지 컨셉 확정 단계',
    sort_order: 1,
    steps: [
      { id: 's1', title: '시장·경쟁사 조사', url: 'https://docs.google.com/spreadsheets/d/EX_SHEET1', done: true },
      { id: 's2', title: '캠페인 컨셉 기획서', url: 'https://docs.google.com/presentation/d/EX_SLIDE1', done: true },
      { id: 's3', title: '채널별 콘텐츠 캘린더', url: 'https://docs.google.com/spreadsheets/d/EX_SHEET2', done: false },
      { id: 's4', title: '성과 측정 리포트 양식', url: 'https://docs.google.com/document/d/EX_DOC1', done: false },
    ],
  },
  {
    id: 'demo-2',
    project: '6월 신제품 런칭',
    team: '영업-마케팅(온라인)',
    title: '상세페이지 카피',
    status: 'planned',
    progress: 0,
    start_date: '2026-06-15',
    due_date: '2026-06-30',
    slides_url: null,
    owner: '조윤성',
    notes: null,
    sort_order: 2,
    steps: [
      { id: 's1', title: '카피 초안', url: 'https://docs.google.com/document/d/EX_DOC2', done: false },
      { id: 's2', title: '디자인 협업 시안', url: 'https://docs.google.com/presentation/d/EX_SLIDE2', done: false },
    ],
  },
  {
    id: 'demo-3',
    project: '6월 신제품 런칭',
    team: '영업-마케팅(오프라인)',
    title: '팝업스토어 운영 준비',
    status: 'in_progress',
    progress: 35,
    start_date: '2026-06-05',
    due_date: '2026-06-25',
    slides_url: 'https://docs.google.com/presentation/d/EXAMPLE2',
    owner: '영업팀',
    notes: null,
    sort_order: 1,
    steps: [
      { id: 's1', title: '장소 섭외 리스트', url: 'https://docs.google.com/spreadsheets/d/EX_SHEET3', done: true },
      { id: 's2', title: '부스 설계안', url: 'https://docs.google.com/presentation/d/EX_SLIDE3', done: false },
    ],
  },
  {
    id: 'demo-4',
    project: '6월 신제품 런칭',
    team: '디자인연구소(개발)',
    title: '신제품 패키지 양산 도면',
    status: 'done',
    progress: 100,
    start_date: '2026-05-20',
    due_date: '2026-06-05',
    slides_url: 'https://docs.google.com/presentation/d/EXAMPLE3',
    owner: '디자인연구소',
    notes: '완료 — 제조본부 전달',
    sort_order: 1,
    steps: [
      { id: 's1', title: '최종 도면', url: 'https://docs.google.com/spreadsheets/d/EX_SHEET4', done: true },
    ],
  },
  {
    id: 'demo-5',
    project: '6월 신제품 런칭',
    team: '제조본부',
    title: '초도 물량 생산',
    status: 'hold',
    progress: 20,
    start_date: '2026-06-10',
    due_date: '2026-06-28',
    slides_url: null,
    owner: '제조본부',
    notes: '자재 입고 대기 중',
    sort_order: 1,
    steps: [],
  },

  // ── 프로젝트: 브랜드 리뉴얼 ──
  {
    id: 'demo-6',
    project: '브랜드 리뉴얼',
    team: '디자인연구소(개발)',
    title: 'BI 리뉴얼 시안',
    status: 'in_progress',
    progress: 45,
    start_date: '2026-06-02',
    due_date: '2026-06-22',
    slides_url: 'https://docs.google.com/presentation/d/EXAMPLE4',
    owner: '디자인연구소',
    notes: null,
    sort_order: 2,
    steps: [
      { id: 's1', title: '무드보드', url: 'https://docs.google.com/presentation/d/EX_SLIDE4', done: true },
      { id: 's2', title: '로고 시안 A/B', url: 'https://docs.google.com/presentation/d/EX_SLIDE5', done: false },
    ],
  },
  {
    id: 'demo-7',
    project: '브랜드 리뉴얼',
    team: '영업-마케팅(온라인)',
    title: '리뉴얼 티저 영상',
    status: 'planned',
    progress: 0,
    start_date: '2026-06-18',
    due_date: '2026-07-05',
    slides_url: null,
    owner: '조윤성',
    notes: null,
    sort_order: 3,
    steps: [],
  },
]
